### ISSUE TITLE
Documentation (oder Schnellbleiche)

### ISSUE THREAD

**Issue by BuckarooBanzay** [joe7575/safer_lua#1]
Is there a documentation or quickstart to use this mod?
**And**: is there a way to provide own values or functions to the execution environment?

I'm looking for an inworld embeddable lua executor and this seems to do that.
The `mesecons_luacontroller` is sadly not usable on its own and also not extendable...

**Comment by joe7575** [comment]
Yes, the documentation is part of the techage Lua controller:  https://github.com/joe7575/techage/blob/master/manuals/ta4_lua_controller_EN.md
or as PDF: https://github.com/joe7575/techage/blob/master/manuals/ta4_lua_controller_EN.pdf

Yes you can add your own functions as it is done here: 
https://github.com/joe7575/safer_lua/blob/master/demo.lua

**Comment by BuckarooBanzay** [comment]
Thank you :+1: this helps a lot

by the way: the "TA4 Lua controller" looks a lot like a Siemens Logo :astonished:
